---
title: "assignment1"
author: "Yilin Zhou(14807009), Zhiyao Lei(), Ziyi Wang()"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Question2.

```{r}
number_payments <- 20
receivable <- c(10000, 20000, 30000)
interest <- c(rep(0.06, 5), rep(0.07, 5), rep(0.08, 12))
yearly_discount_factors <- (1 + interest) ^ -1
discount_factors <- c(1, cumprod(yearly_discount_factors))
payment_pattern <- (1 - 0.05) ^ (0:(number_payments - 1))
K <- sum(receivable * discount_factors[1:3]) / sum(payment_pattern * discount_factors[4:23])
payments <- K * payment_pattern
for (i in 3:22){
  cat(sprintf("t = %2.d should pay: %.5f \n", i, payments[i - 2]))
}
```

## Including Plots


##Question3

#3.1
```{r}
i <- 0.055
#define the monthly interest rate i_m
i_m <- i / 12
discount_factors <- (1 + i_m) ^ - (0:(12 * 15))
payment <- c(150000, rep(-1225.63, 12 * 15))
PV <- sum(payment * discount_factors)
cat(PV)
```


#3.2

A house priced 700000 euro, suppose we have 140000 avaliable, which means we need to borrow left 80% (560000euro), the interest rate for 20 years is 0.0429, we need to pay 3,479.67 monthly according to the online calculator.
```{r}
i <- 0.0429
i_m <- i / 12
discount_factors <- (1 + i_m) ^ - (1:240)
payment_pattern <- rep(1, 240)
K <- 560000 / sum(payment_pattern * discount_factors)
cat(K)
```